version: '3.8'

services:
  web:
    image: docker-prueba:latest
    ports:
      - "8000:8000"
    volumes:
      - ./app:/code/app
    environment:
      - MONGODB_URL=mongodb://db:27017
      - DB_NAME=test
    depends_on:
      - db

  db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: